#!/usr/bin/perl

use Audio::PortAudio;
use IO::File;

my $api = Audio::PortAudio::default_host_api();
my $wdevice = $api->default_output_device;

my $sample_rate = 22050;
my $frames_per_buffer = 100;
my $flags = 0;
my $number_of_frames = 1600;
my $stream_flags = '';

my $buffsize = 12800;

my $buffer = "";
my $maxbuffers = 1000;

my $wstream = $wdevice->open_write_stream( {
					    channel_count => 2,
					    sample_format => 'float32'
					   },
					   $sample_rate,
					   $frames_per_buffer,
					   $stream_flags
					 );
$| = 1;

my $worthylimit = .002;

sub max {
    return $_[0] if ($_[0] > $_[1]);
    return $_[1];
}

foreach my $file (@ARGV) {
    my $fh = IO::File->new();
    $fh->open($file);
    die "couldn't open $file\n" if (!$fh);
    my $buffer;
    print "$file: ";
  top:
    while ($fh->read($buffer, $buffsize)) {
	my @vals = unpack "f*", $buffer;
#	printf("vals ($#vals): %f %f %f %f\n", @vals);
	for (my $i = 0; $i <= $#vals; $i++) {
	    if ($vals[$i] >= $worthylimit || $vals <= -$worthylimit) {
		print "+";
		$wstream->write($buffer);
		next top;
	    }
	}
	print "-";
    }
    print"\n";
}

